---
- hosts: all
  user: vagrant
  become: yes
  become_user: root

  tasks:
    - name: Install users
      user: name={{ item }} state=present
      with_items:
        - neguentropia

    - name: Authorized_key - root
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Authorized_key - neguentropia
      authorized_key:
        user: neguentropia
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: dotdeb apt key
      apt_key:
        url: "https://www.dotdeb.org/dotdeb.gpg"
        validate_certs: no
        state: present


    - name: Update dist
      apt:
        upgrade: dist


    - name: Install packages
      apt: name={{ item }} state=installed force=yes
      with_items:
        - nginx
        - php7.0
        - php7.0-fpm
        - php7.0-curl
        - php7.0-json
        - php7.0-gd
        - php7.0-mcrypt
        - php7.0-msgpack
        - php7.0-memcached
        - php7.0-intl
        - php7.0-sqlite3
        - php7.0-gmp
        - php7.0-geoip
        - php7.0-mbstring
        - php7.0-xml
        - php7.0-zip
