---
- hosts: all
  user: vagrant
  become: yes
  become_user: root

  tasks:
    - name: Install users
      user: name={{ item }} state=present shell=/bin/bash
      with_items: "{{ sys_users }}"

    - name: Ensure .ssh folder exists
      file: path=~{{ item }}/.ssh state=directory
      with_items: "{{ sys_users }}"

    - name: Set authorized_keys
      template:
        src: configs/authorized_keys
        dest: ~{{ item }}/.ssh/authorized_keys
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0600
      with_items: "{{ sys_users }}" 

    - name: Install sudoers
      template:
        src: configs/sudoers
        dest: /etc/sudoers.d/{{ item }}
      with_items:
        - "{{ hostname }}"

    - name: dotdeb apt key
      apt_key:
        url: "https://www.dotdeb.org/dotdeb.gpg"
        validate_certs: no
        state: present

    - name: dotdeb aptrepository
      apt_repository:
        repo: deb http://packages.dotdeb.org jessie all
        state: present


    - name: Update dist
      apt:
        upgrade: dist


    - name: Init run_once folder
      file:
        path: /opt/provisioned
        state: directory
        mode: 0644

    - name: Init download folder
      file:
        path: /opt/download
        state: directory
        mode: 0644

    - name: Install packages - commons
      apt: name={{ item }} state=installed force=yes
      with_items: "{{ sys_packages }}"

    - name: Install specific packages
      apt: name={{ item }} state=installed force=yes
      with_items: "{{ host_packages }}"

    - include: install_{{ hostname }}.yml
      tags: [ custom ]

