---
- name: Write nginx config files
  template:
    src: configs/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Write {{ host }} config files
  template:
    src: configs/nginx/{{ hostname }}.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Install nodejs
  script: scripts/install-nodejs.sh {{ node_version}}
  args:
    creates: /opt/provisioned/node-{{ node_version }}

- name: Npm global packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - yarn
    - vue-cli

- file:
    src: '/usr/local/node/bin/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    state: link
  with_items:
    - vue
    - vue-init
    - vue-list
    - vue-build
    - yarn
    - yarnpkg
